# Generated by Django 3.1.3 on 2020-11-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
